DWAPlannerROS:
  #Robot Configuration Parameters
  acc_lim_x: 2.5 #default: 2.5
  acc_lim_y: 2.5 #default: 2.5
  acc_lim_th: 3.2 #default: 3.2
  max_trans_vel: 0.55 #default: 0.55
  min_trans_vel: 0.1 #default: 0.1
  max_vel_x: 0.55 #default 0.55
  min_vel_x: 0.0 #default: 0.0
  max_vel_y: 0.1 #default: 0.1
  min_vel_y: -0.1 #default: -0.1
  max_rot_vel: 1.0 #default: 1.0
  min_rot_vel: 0.4 #default: 0.4  
  
  #Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05 #default: 0.05
  xy_goal_tolerance: 0.1 #default: 0.1
  latch_xy_goal_tolerance: false #default: false

  #Forward Simulation Parameters
  sim_time: 2.0 #default: 1.7
  sim_granularity: 0.05 #default: 0.025
  vx_samples: 10 #default: 3
  vy_samples: 10 #default: 10
  vtheta_samples: 15 #default: 20
  penalize_negative_x: false #default: true

  #Trajectory Scoring Parameters
  path_distance_bias: 32.0 #default: 32.0
  goal_distance_bias: 24.0 #default: 24.0
  occdist_scale: 0.01 #default: 0.01
  forward_point_distance: 0.325 #default: 0.325
  stop_time_buffer: 0.2 #default: 0.2
  scaling_speed: 0.25 #default: 0.25
  max_scaling_factor: 0.2 #default: 0.2
 
  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #default: 0.05

  #Global Plan Parameters
  prune_plan: true #default: true

  publish_cost_grid_pc: true
  publish_traj_pc: true