global_frame: /map
robot_base_frame: base_link
footprint: [[-0.25, -0.225], [-0.325, 0], [-0.25, 0.225], [0.25, 0.225], [0.325, 0], [0.25, -0.225]]
update_frequency: 5.0
publish_frequency: 2.0
map_type: costmap
transform_tolerance: 0.5
static_map: true
rolling_window: false
plugins:
  - {name: static_map,       type: "costmap_2d::StaticLayer"}
  - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}

obstacles:
  track_unknown_space: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /rrbot/laser/scan, marking: true, clearing: true, expected_update_rate: 0.1}
  
publish_cost_grid: true