global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: true
  transform_tolerance: 0.5
  
  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    - {name: proxemics,        type: "hanp_costmap_layers/ProxemicsLayer"}
    - {name: visibility,       type: "hanp_costmap_layers/VisibilityLayer"}
    - {name: pass_on_left,     type: "hanp_costmap_layers/Pass_On_LeftLayer"}
    - {name: interaction,      type: "hanp_costmap_layers/InteractionLayer"}
    
  footprint: [[-0.25, -0.225], [-0.325, 0], [-0.25, 0.225], [0.25, 0.225], [0.325, 0], [0.25, -0.225]]

  obstacles:
      track_unknown_space: true
      obstacle_range: 2.5
      raytrace_range: 3.0
      observation_sources: laser_scan_sensor
      laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /rrbot/laser/scan, marking: true, clearing: true, expected_update_rate: 0.5} 


  inflation_radius: 0.5
  transform_tolerance: 0.5
  map_type: costmap
  publish_cost_grid: true
  origin_x: -12.800000 
  origin_y: -12.800000