local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  map_type: costmap
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0
  plugins:
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    - {name: proxemics,        type: "hannrs_costmap_layers/ProxemicsLayer"}
    - {name: visibility,       type: "hannrs_costmap_layers/VisibilityLayer"}
    - {name: pass_on_left,     type: "hannrs_costmap_layers/Pass_On_LeftLayer"}
    - {name: interaction,      type: "hannrs_costmap_layers/InteractionLayer"}
    
  obstacles:
    track_unknown_space: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /rrbot/laser/scan, marking: true, clearing: true, expected_update_rate: 0.1} 
  
  publish_cost_grid: true
  
global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  map_type: costmap
  transform_tolerance: 0.5
  static_map: true
  rolling_window: false
  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    - {name: proxemics,        type: "hannrs_costmap_layers/ProxemicsLayer"}
    - {name: visibility,       type: "hannrs_costmap_layers/VisibilityLayer"}
    - {name: pass_on_left,     type: "hannrs_costmap_layers/Pass_On_LeftLayer"}
    - {name: interaction,      type: "hannrs_costmap_layers/InteractionLayer"}
    
  obstacles:
    track_unknown_space: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /rrbot/laser/scan, marking: true, clearing: true, expected_update_rate: 0.1}
    
  publish_cost_grid: true