local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  map_type: costmap
  transform_tolerance: 1.5
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  plugins:
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    - {name: proxemics,        type: "hannrs_costmap_layers/ProxemicsLayer"}
    - {name: visibility,       type: "hannrs_costmap_layers/VisibilityLayer"}
    - {name: pass_on_left,     type: "hannrs_costmap_layers/Pass_On_LeftLayer"}
    - {name: interaction,      type: "hannrs_costmap_layers/InteractionLayer"}
    
  obstacles:
    track_unknown_space: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    observation_sources: laser_scan_sensor1 laser_scan_sensor2
    laser_scan_sensor1: {sensor_frame: lrf01, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.2}
    laser_scan_sensor2: {sensor_frame: lrf02, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.2}
  
  inflation:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0

  publish_cost_grid: false

  
global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 1.0
  map_type: costmap
  transform_tolerance: 1.5
  static_map: true
  rolling_window: false
  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
    - {name: proxemics,        type: "hannrs_costmap_layers/ProxemicsLayer"}
    - {name: visibility,       type: "hannrs_costmap_layers/VisibilityLayer"}
    - {name: pass_on_left,     type: "hannrs_costmap_layers/Pass_On_LeftLayer"}
    - {name: interaction,      type: "hannrs_costmap_layers/InteractionLayer"}

  obstacles:
    track_unknown_space: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    observation_sources: laser_scan_sensor1 laser_scan_sensor2
    laser_scan_sensor1: {sensor_frame: lrf01, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.2}
    laser_scan_sensor2: {sensor_frame: lrf02, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 0.2}
    
  inflation:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0

  publish_cost_grid: false
