TrajectoryPlannerROS:
  #Robot Configuration Parameters
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  acc_lim_theta: 2.2
  max_vel_x: 0.55
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.25
  escape_vel: -0.1
  holonomic_robot: true
  y_vels: [-0.25 -0.1 0.1 0.25]
  
  #Goal Tolerance Parameters
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  
  #Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.05
  angular_sim_granularity: 0.05
  vx_samples: 8
  vtheta_samples: 20
  
  #Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.8
  gdist_scale: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: false
  
  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  
  #Global Plan Parameters
  prune_plan: true
  
  publish_cost_grid_pc: true
  publish_traj_pc: true
