// Generated by gencpp from file hannrs_msgs/InteractionSets.msg
// DO NOT EDIT!


#ifndef HANNRS_MSGS_MESSAGE_INTERACTIONSETS_H
#define HANNRS_MSGS_MESSAGE_INTERACTIONSETS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hannrs_msgs/InteractionSet.h>

namespace hannrs_msgs
{
template <class ContainerAllocator>
struct InteractionSets_
{
  typedef InteractionSets_<ContainerAllocator> Type;

  InteractionSets_()
    : header()
    , interaction_sets()  {
    }
  InteractionSets_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , interaction_sets(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hannrs_msgs::InteractionSet_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hannrs_msgs::InteractionSet_<ContainerAllocator> >::other >  _interaction_sets_type;
  _interaction_sets_type interaction_sets;




  typedef boost::shared_ptr< ::hannrs_msgs::InteractionSets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hannrs_msgs::InteractionSets_<ContainerAllocator> const> ConstPtr;

}; // struct InteractionSets_

typedef ::hannrs_msgs::InteractionSets_<std::allocator<void> > InteractionSets;

typedef boost::shared_ptr< ::hannrs_msgs::InteractionSets > InteractionSetsPtr;
typedef boost::shared_ptr< ::hannrs_msgs::InteractionSets const> InteractionSetsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hannrs_msgs::InteractionSets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hannrs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hannrs_msgs': ['/home/amateus/HANNRS/catkin_ws/src/hannrs_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hannrs_msgs::InteractionSets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hannrs_msgs::InteractionSets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hannrs_msgs::InteractionSets_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ded484679810030225d5056ea06c63e";
  }

  static const char* value(const ::hannrs_msgs::InteractionSets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ded484679810030ULL;
  static const uint64_t static_value2 = 0x225d5056ea06c63eULL;
};

template<class ContainerAllocator>
struct DataType< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hannrs_msgs/InteractionSets";
  }

  static const char* value(const ::hannrs_msgs::InteractionSets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
hannrs_msgs/InteractionSet[] interaction_sets\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: hannrs_msgs/InteractionSet\n\
geometry_msgs/Point center\n\
std_msgs/Float64 radius\n\
std_msgs/Float64 importance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::hannrs_msgs::InteractionSets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.interaction_sets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct InteractionSets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hannrs_msgs::InteractionSets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hannrs_msgs::InteractionSets_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "interaction_sets[]" << std::endl;
    for (size_t i = 0; i < v.interaction_sets.size(); ++i)
    {
      s << indent << "  interaction_sets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hannrs_msgs::InteractionSet_<ContainerAllocator> >::stream(s, indent + "    ", v.interaction_sets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANNRS_MSGS_MESSAGE_INTERACTIONSETS_H
