// Generated by gencpp from file hannrs_msgs/Prox_GoalResponse.msg
// DO NOT EDIT!


#ifndef HANNRS_MSGS_MESSAGE_PROX_GOALRESPONSE_H
#define HANNRS_MSGS_MESSAGE_PROX_GOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>

namespace hannrs_msgs
{
template <class ContainerAllocator>
struct Prox_GoalResponse_
{
  typedef Prox_GoalResponse_<ContainerAllocator> Type;

  Prox_GoalResponse_()
    : wait_time()  {
    }
  Prox_GoalResponse_(const ContainerAllocator& _alloc)
    : wait_time(_alloc)  {
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _wait_time_type;
  _wait_time_type wait_time;




  typedef boost::shared_ptr< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Prox_GoalResponse_

typedef ::hannrs_msgs::Prox_GoalResponse_<std::allocator<void> > Prox_GoalResponse;

typedef boost::shared_ptr< ::hannrs_msgs::Prox_GoalResponse > Prox_GoalResponsePtr;
typedef boost::shared_ptr< ::hannrs_msgs::Prox_GoalResponse const> Prox_GoalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hannrs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hannrs_msgs': ['/home/amateus/HANNRS/catkin_ws/src/hannrs_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6633c18676170982ec546c15661654cb";
  }

  static const char* value(const ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6633c18676170982ULL;
  static const uint64_t static_value2 = 0xec546c15661654cbULL;
};

template<class ContainerAllocator>
struct DataType< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hannrs_msgs/Prox_GoalResponse";
  }

  static const char* value(const ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 wait_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wait_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Prox_GoalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hannrs_msgs::Prox_GoalResponse_<ContainerAllocator>& v)
  {
    s << indent << "wait_time: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.wait_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANNRS_MSGS_MESSAGE_PROX_GOALRESPONSE_H
