// Generated by gencpp from file hannrs_msgs/Prox_Goal.msg
// DO NOT EDIT!


#ifndef HANNRS_MSGS_MESSAGE_PROX_GOAL_H
#define HANNRS_MSGS_MESSAGE_PROX_GOAL_H

#include <ros/service_traits.h>


#include <hannrs_msgs/Prox_GoalRequest.h>
#include <hannrs_msgs/Prox_GoalResponse.h>


namespace hannrs_msgs
{

struct Prox_Goal
{

typedef Prox_GoalRequest Request;
typedef Prox_GoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Prox_Goal
} // namespace hannrs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hannrs_msgs::Prox_Goal > {
  static const char* value()
  {
    return "8e39ad254c03e98e247f822ee5a87824";
  }

  static const char* value(const ::hannrs_msgs::Prox_Goal&) { return value(); }
};

template<>
struct DataType< ::hannrs_msgs::Prox_Goal > {
  static const char* value()
  {
    return "hannrs_msgs/Prox_Goal";
  }

  static const char* value(const ::hannrs_msgs::Prox_Goal&) { return value(); }
};


// service_traits::MD5Sum< ::hannrs_msgs::Prox_GoalRequest> should match 
// service_traits::MD5Sum< ::hannrs_msgs::Prox_Goal > 
template<>
struct MD5Sum< ::hannrs_msgs::Prox_GoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hannrs_msgs::Prox_Goal >::value();
  }
  static const char* value(const ::hannrs_msgs::Prox_GoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hannrs_msgs::Prox_GoalRequest> should match 
// service_traits::DataType< ::hannrs_msgs::Prox_Goal > 
template<>
struct DataType< ::hannrs_msgs::Prox_GoalRequest>
{
  static const char* value()
  {
    return DataType< ::hannrs_msgs::Prox_Goal >::value();
  }
  static const char* value(const ::hannrs_msgs::Prox_GoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hannrs_msgs::Prox_GoalResponse> should match 
// service_traits::MD5Sum< ::hannrs_msgs::Prox_Goal > 
template<>
struct MD5Sum< ::hannrs_msgs::Prox_GoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hannrs_msgs::Prox_Goal >::value();
  }
  static const char* value(const ::hannrs_msgs::Prox_GoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hannrs_msgs::Prox_GoalResponse> should match 
// service_traits::DataType< ::hannrs_msgs::Prox_Goal > 
template<>
struct DataType< ::hannrs_msgs::Prox_GoalResponse>
{
  static const char* value()
  {
    return DataType< ::hannrs_msgs::Prox_Goal >::value();
  }
  static const char* value(const ::hannrs_msgs::Prox_GoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANNRS_MSGS_MESSAGE_PROX_GOAL_H
