// Generated by gencpp from file hannrs_msgs/VisionDetection.msg
// DO NOT EDIT!


#ifndef HANNRS_MSGS_MESSAGE_VISIONDETECTION_H
#define HANNRS_MSGS_MESSAGE_VISIONDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace hannrs_msgs
{
template <class ContainerAllocator>
struct VisionDetection_
{
  typedef VisionDetection_<ContainerAllocator> Type;

  VisionDetection_()
    : header()
    , positions()
    , classifications()
    , camera()  {
    }
  VisionDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , positions(_alloc)
    , classifications(_alloc)
    , camera(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _classifications_type;
  _classifications_type classifications;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _camera_type;
  _camera_type camera;




  typedef boost::shared_ptr< ::hannrs_msgs::VisionDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hannrs_msgs::VisionDetection_<ContainerAllocator> const> ConstPtr;

}; // struct VisionDetection_

typedef ::hannrs_msgs::VisionDetection_<std::allocator<void> > VisionDetection;

typedef boost::shared_ptr< ::hannrs_msgs::VisionDetection > VisionDetectionPtr;
typedef boost::shared_ptr< ::hannrs_msgs::VisionDetection const> VisionDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hannrs_msgs::VisionDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hannrs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'hannrs_msgs': ['/home/amateus/HANNRS/catkin_ws/src/hannrs_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hannrs_msgs::VisionDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hannrs_msgs::VisionDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hannrs_msgs::VisionDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14445a7b0a15418cdcb6155f2f316869";
  }

  static const char* value(const ::hannrs_msgs::VisionDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14445a7b0a15418cULL;
  static const uint64_t static_value2 = 0xdcb6155f2f316869ULL;
};

template<class ContainerAllocator>
struct DataType< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hannrs_msgs/VisionDetection";
  }

  static const char* value(const ::hannrs_msgs::VisionDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point[] positions\n\
float32[] classifications\n\
string camera\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::hannrs_msgs::VisionDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.positions);
      stream.next(m.classifications);
      stream.next(m.camera);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct VisionDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hannrs_msgs::VisionDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hannrs_msgs::VisionDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
    s << indent << "classifications[]" << std::endl;
    for (size_t i = 0; i < v.classifications.size(); ++i)
    {
      s << indent << "  classifications[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.classifications[i]);
    }
    s << indent << "camera: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANNRS_MSGS_MESSAGE_VISIONDETECTION_H
