(cl:defpackage hannrs_msgs-srv
  (:use )
  (:export
   "PROX_GOAL"
   "<PROX_GOAL-REQUEST>"
   "PROX_GOAL-REQUEST"
   "<PROX_GOAL-RESPONSE>"
   "PROX_GOAL-RESPONSE"
   "GET_PERSON"
   "<GET_PERSON-REQUEST>"
   "GET_PERSON-REQUEST"
   "<GET_PERSON-RESPONSE>"
   "GET_PERSON-RESPONSE"
  ))

